### PR TITLE
ENTMQBR-2629 Ensure sensitive credentials are stored in kubernetes secrets

### PR DESCRIPTION
**Pull request by gaohoward**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by RoddieKieley — COMMENTED** [review]
@gaohoward This didn't work for me out of the box using the amq-broker-73-persistence-clustered-ssl template. 
I processed it this way:
$ oc process -n amq73-p-c-ssl-3 -f templates/amq-broker-73-persistence-clustered-ssl.yaml -p APPLICATION_NAME=application0 -p AMQ_USER=admin -p AMQ_PASSWORD=admin -p AMQ_NAME=amq0 -p AMQ_
EXTRA_ARGS=--no-autotune -p AMQ_KEYSTORE=broker.ks -p AMQ_TRUSTSTORE=broker.ts -p AMQ_KEYSTORE_PASSWORD=password -p AMQ_TRUSTSTORE_PASSWORD=password | oc create -f -

But on startup I get
.
.
.
2019-07-19 12:59:01,445 INFO  [io.hawt.system.ProxyWhitelist] Initial proxy whitelist: [localhost, 127.0.0.1, 10.130.0.8, application0-amq-0.amq0-amq-headless.amq73-p-c-ssl-3.svc.cluster.local]
java.io.IOException: Invalid keystore format
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:663)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
.
.
.

And when I look at the mounted amq-secret-volume what I see seems a little odd:

h-4.2$ cd amq-secret-volume/
sh-4.2$ ls
admin  broker.ks  broker.ts  eQgWDYgr  password  userWre
sh-4.2$ ls -latrh
total 0
lrwxrwxrwx. 1 root root        14 Jul 19 12:57 userWre -> ..data/userWre
lrwxrwxrwx. 1 root root        15 Jul 19 12:57 password -> ..data/password
lrwxrwxrwx. 1 root root        15 Jul 19 12:57 eQgWDYgr -> ..data/eQgWDYgr
lrwxrwxrwx. 1 root root        16 Jul 19 12:57 broker.ts -> ..data/broker.ts
lrwxrwxrwx. 1 root root        16 Jul 19 12:57 broker.ks -> ..data/broker.ks
lrwxrwxrwx. 1 root root        12 Jul 19 12:57 admin -> ..data/admin
lrwxrwxrwx. 1 root root        31 Jul 19 12:57 ..data -> ..2019_07_19_12_57_53.631931779
drwxr-sr-x. 2 root 1000760000 160 Jul 19 12:57 ..2019_07_19_12_57_53.631931779
drwxrwsrwt. 3 root 1000760000 200 Jul 19 12:57 .
drwxr-xr-x. 1 root root        31 Jul 19 12:58 ..
sh-4.2$

Does the new configuration require a different processing?

**Comment by gaohoward** [comment]
@RoddieKieley Hi Roddie,
I think that your broker.ks (as mounted in ../data/broker.ks) may not be in correct format.
When you pass "-p AMQ_KEYSTORE=broker.ks" into the template the real value for AMQ_KEYSTORE
will be retrieved from secret (default is "broker.ks" in base64 form in the template file).

Can you pass me the broker.ks (and maybe the broker.ts too)?

Howard

**Comment by gaohoward** [comment]
@RoddieKieley  I think there is a problem in how I used the secret store for the keystore/truststore.
I'm investigating...

**Comment by gaohoward** [comment]
@RoddieKieley  Hi Roddie, I updated my PR and it should work now. Please review again.

**Comment by RoddieKieley** [comment]
@gaohoward Manually rebased on amq-broker-74-dev committed at [6164487ddb006a75a47cfea31da4d761da24e0df](https://github.com/jboss-container-images/jboss-amq-7-broker-openshift-image/commit/6164487ddb006a75a47cfea31da4d761da24e0df)

**Comment by jbyrne-redhat** [comment]
Hi, @howardgao @RoddieKieley 

I took a look at https://github.com/jboss-container-images/jboss-amq-7-broker-openshift-image/commit/6164487ddb006a75a47cfea31da4d761da24e0df to understand the solution, but there's quite a bit going on there!

Can you give me a brief description of what users must now do to pass in variables such as AMQ_USER, AMQ_PASSWORD, AMQ_CLUSTER_USER, and AMQ_CLUSTER_PASSWORD? Is a secret automatically created for them when they first deploy the template, with the secret name specified in AMQ_CREDENTIAL_SECRET?

An additional question: how do they modify the credentials?

**Comment by fvaleri** [comment]
@gaohoward I understand the need for this change, but, given the parameter names, having to put keys inside them is really counter intuitive. This is also a change in behavior for these variables.

**Pull request closed without merging**
